table COGs1
	lineageTag: ffc18878-ad57-4ef4-936b-991c95c13ff0

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 440fe6cb-6cb5-42da-a1ef-1f20d6e7ff3c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Category
		dataType: string
		lineageTag: e453d795-aff6-481f-9edf-826be8cd9113
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 21b5c606-6a57-4bbf-bc80-aa9b823a5994
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

	partition COGs1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://jetcontainercompany.sharepoint.com/sites/ContinuousImprovement/Shared%20Documents/General/Employee%20of%20the%20Month,%20COGs,%20Upcoming%20Shutdowns.xlsx"), null, true),
				    COGs_Table = Source{[Item="COGs",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(COGs_Table,{{"Date", type date}, {"Category", type text}, {"Cost", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

