table dwproductionfeedback
	lineageTag: 475cf774-3cc8-4a7b-a271-1c1166fe0cc7

	column feedback_id
		dataType: int64
		formatString: 0
		lineageTag: a7afe02a-e593-4037-bad7-aa2ad26c830f
		summarizeBy: sum
		sourceColumn: feedback_id

		annotation SummarizationSetBy = Automatic

	column feedback_job_series_step_id
		dataType: int64
		formatString: 0
		lineageTag: 55441685-6a0a-4569-8bf8-3b82ea4fd064
		summarizeBy: none
		sourceColumn: feedback_job_series_step_id

		annotation SummarizationSetBy = Automatic

	column feedback_date_id
		dataType: int64
		formatString: 0
		lineageTag: 3625aae3-1515-42c6-b6a4-83f6b34f8fa1
		summarizeBy: none
		sourceColumn: feedback_date_id

		annotation SummarizationSetBy = Automatic

	column setup_duration_minutes
		dataType: int64
		formatString: 0
		lineageTag: 8e08610a-b2aa-4778-8e8c-e84e1650f549
		summarizeBy: sum
		sourceColumn: setup_duration_minutes

		annotation SummarizationSetBy = Automatic

	column actual_setup_duration_minutes
		dataType: int64
		formatString: 0
		lineageTag: cdff254c-023f-4653-8eb9-29fa636ddc21
		summarizeBy: sum
		sourceColumn: actual_setup_duration_minutes

		annotation SummarizationSetBy = Automatic

	column setup_duration_seconds
		dataType: int64
		formatString: 0
		lineageTag: 39e5e77a-30e2-4181-9281-0b9786c52a2d
		summarizeBy: sum
		sourceColumn: setup_duration_seconds

		annotation SummarizationSetBy = Automatic

	column actual_setup_duration_seconds
		dataType: int64
		formatString: 0
		lineageTag: 650e0189-04c5-4486-85bf-5fe85e450021
		summarizeBy: sum
		sourceColumn: actual_setup_duration_seconds

		annotation SummarizationSetBy = Automatic

	column run_duration_minutes
		dataType: int64
		formatString: 0
		lineageTag: 6f531c8e-0577-4307-830d-46866ab75be4
		summarizeBy: sum
		sourceColumn: run_duration_minutes

		annotation SummarizationSetBy = Automatic

	column actual_run_duration_minutes
		dataType: int64
		formatString: 0
		lineageTag: aa678ede-bfe6-46a5-a77b-30260c5efbcf
		summarizeBy: sum
		sourceColumn: actual_run_duration_minutes

		annotation SummarizationSetBy = Automatic

	column run_duration_seconds
		dataType: int64
		formatString: 0
		lineageTag: 45212b34-ee76-4f02-a7d0-81af4d030f52
		summarizeBy: sum
		sourceColumn: run_duration_seconds

		annotation SummarizationSetBy = Automatic

	column actual_run_duration_seconds
		dataType: int64
		formatString: 0
		lineageTag: 69d5d2dc-6bf5-44b5-b659-a99b0bc05fa5
		summarizeBy: sum
		sourceColumn: actual_run_duration_seconds

		annotation SummarizationSetBy = Automatic

	column quantity_ordered
		dataType: int64
		formatString: 0
		lineageTag: e4e6736d-c424-45e5-9b8c-9d8c91326f78
		summarizeBy: sum
		sourceColumn: quantity_ordered

		annotation SummarizationSetBy = Automatic

	column quantity_fed_in
		dataType: int64
		formatString: 0
		lineageTag: 714977c3-2f40-4cca-81e9-eb31b70f1828
		summarizeBy: sum
		sourceColumn: quantity_fed_in

		annotation SummarizationSetBy = Automatic

	column prerun_waste
		dataType: int64
		formatString: 0
		lineageTag: c74cf4cd-4666-41e6-a203-06cb1954a75a
		summarizeBy: sum
		sourceColumn: prerun_waste

		annotation SummarizationSetBy = Automatic

	column setup_waste
		dataType: int64
		formatString: 0
		lineageTag: a0c10657-5ba8-4f3c-b052-1701a99b9969
		summarizeBy: sum
		sourceColumn: setup_waste

		annotation SummarizationSetBy = Automatic

	column quantity_fed
		dataType: int64
		formatString: 0
		lineageTag: 1623daa8-afed-4924-8e5a-0b6c97ef396b
		summarizeBy: sum
		sourceColumn: quantity_fed

		annotation SummarizationSetBy = Automatic

	column quantity_produced
		dataType: int64
		formatString: 0
		lineageTag: acadba7a-2030-4dfa-ad12-8246c47ac129
		summarizeBy: sum
		sourceColumn: quantity_produced

		annotation SummarizationSetBy = Automatic

	column entry_length
		dataType: int64
		formatString: 0
		lineageTag: 4b3192e2-6873-4c23-9ca5-798f4e5967bc
		summarizeBy: sum
		sourceColumn: entry_length

		annotation SummarizationSetBy = Automatic

	column entry_width
		dataType: int64
		formatString: 0
		lineageTag: a0ad2453-0024-46d6-8d0b-4d1159f2ff59
		summarizeBy: sum
		sourceColumn: entry_width

		annotation SummarizationSetBy = Automatic

	column exit_length
		dataType: int64
		formatString: 0
		lineageTag: 5639a810-9fd0-4388-a8e5-ccc2a7bcd678
		summarizeBy: sum
		sourceColumn: exit_length

		annotation SummarizationSetBy = Automatic

	column exit_width
		dataType: int64
		formatString: 0
		lineageTag: 9cd2ec3a-1c7e-4bd6-b325-4d3c8e537cdb
		summarizeBy: sum
		sourceColumn: exit_width

		annotation SummarizationSetBy = Automatic

	column ontime_variance_minutes
		dataType: int64
		formatString: 0
		lineageTag: 5c540f16-ec7a-4b9b-a707-bcf4fe1387c6
		summarizeBy: sum
		sourceColumn: ontime_variance_minutes

		annotation SummarizationSetBy = Automatic

	column planned_setup_time
		dataType: int64
		formatString: 0
		lineageTag: 988aa34a-68f5-41ef-9469-69d1d83ff108
		summarizeBy: sum
		sourceColumn: planned_setup_time

		annotation SummarizationSetBy = Automatic

	column planned_run_speed
		dataType: int64
		formatString: 0
		lineageTag: b08e8882-84b8-4425-a0ff-8503f2d62f3f
		summarizeBy: sum
		sourceColumn: planned_run_speed

		annotation SummarizationSetBy = Automatic

	column planned_quantity
		dataType: int64
		formatString: 0
		lineageTag: 2c5d8f2f-9751-48a4-8d22-f39f9b444ac4
		summarizeBy: sum
		sourceColumn: planned_quantity

		annotation SummarizationSetBy = Automatic

	column area_entry
		dataType: int64
		formatString: 0
		lineageTag: c7855a1c-3672-4a98-8bdd-ea2a69ecc570
		summarizeBy: sum
		sourceColumn: area_entry

		annotation SummarizationSetBy = Automatic

	column area_exit
		dataType: int64
		formatString: 0
		lineageTag: ace42421-8422-4224-a79b-2aeb577d8add
		summarizeBy: sum
		sourceColumn: area_exit

		annotation SummarizationSetBy = Automatic

	column target_speed
		dataType: int64
		formatString: 0
		lineageTag: a27e8f39-fee5-4144-8421-455a02b983cd
		summarizeBy: sum
		sourceColumn: target_speed

		annotation SummarizationSetBy = Automatic

	column area_produced
		dataType: int64
		formatString: 0
		lineageTag: 172b3c0f-7fed-42e4-b1ca-f28c193ad152
		summarizeBy: sum
		sourceColumn: area_produced

		annotation SummarizationSetBy = Automatic

	column 'actual run hours' = dwproductionfeedback[actual_run_duration_seconds]/60/60
		formatString: 0.00
		lineageTag: b32ec32e-e4e7-4456-9a5f-793254875975
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'actual sheets fed per hour' = dwproductionfeedback[quantity_fed_in]/dwproductionfeedback[actual run hours]
		formatString: 0
		lineageTag: 25030104-f8b3-46ae-bddb-10f9486f096f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Line Number'
		dataType: string
		lineageTag: 074579c4-519f-4b66-98e0-bc5c8b1a2817
		summarizeBy: none
		sourceColumn: Line Number

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'dwcostcenters.costcenter_name'
		dataType: string
		lineageTag: 0098ac49-5c3f-4e76-8e45-92fece3980ae
		summarizeBy: none
		sourceColumn: dwcostcenters.costcenter_name

		annotation SummarizationSetBy = Automatic

	column 'dwcostcenters.optimum_run_speed'
		dataType: int64
		formatString: 0
		lineageTag: d85c7ee8-1988-4e90-97dc-96c83cf6fe41
		summarizeBy: sum
		sourceColumn: dwcostcenters.optimum_run_speed

		annotation SummarizationSetBy = Automatic

	column 'dwproductionorders.spec_number'
		dataType: string
		lineageTag: f31ebae8-4e93-41f4-aabc-f9f03974597b
		summarizeBy: none
		sourceColumn: dwproductionorders.spec_number

		annotation SummarizationSetBy = Automatic

	column 'dwproductionorders.job_number'
		dataType: string
		lineageTag: 8c023ca4-ee0c-4a68-a7d9-d19e603b5e8f
		summarizeBy: none
		sourceColumn: dwproductionorders.job_number

		annotation SummarizationSetBy = Automatic

	column 'week start date' = dwproductionfeedback[feedback_report_date] - WEEKDAY(dwproductionfeedback[feedback_report_date],3)
		formatString: Short Date
		lineageTag: 72ff8383-e3d1-4213-8d95-6f0545df3d7f
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 3d7fdd7e-922b-4b12-9068-470dcf468c54
			defaultHierarchy: LocalDateTable_99021944-e550-4d3a-8923-a1e317bbb18f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Machine Name & #' = dwproductionfeedback[Line Number] & " " & dwproductionfeedback[dwcostcenters.costcenter_name]
		lineageTag: 13c7714f-07be-4281-89ce-ff46927d9591
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'rolled up wasted quantity reported' = IF(CALCULATE(Sum(dwwaste[Wasted Quantity]),RELATEDTABLE(dwwaste))>200000,0,CALCULATE(Sum(dwwaste[Wasted Quantity]),RELATEDTABLE(dwwaste)))
		formatString: 0
		lineageTag: 15db0955-64a4-4a5d-9f6a-1ba6913633f9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'dwjobseriesstep.number_up_entry_1'
		dataType: int64
		formatString: 0
		lineageTag: a9c85231-6d0b-4e09-9734-dbae45526066
		summarizeBy: sum
		sourceColumn: dwjobseriesstep.number_up_entry_1

		annotation SummarizationSetBy = Automatic

	column 'dwjobseriesstep.number_up_exit_1'
		dataType: int64
		formatString: 0
		lineageTag: 5db966e9-59ef-48d5-b62a-6bbb1e268f0e
		summarizeBy: sum
		sourceColumn: dwjobseriesstep.number_up_exit_1

		annotation SummarizationSetBy = Automatic

	column 'Number out (entry/exit)' = dwproductionfeedback[dwjobseriesstep.number_up_entry_1]/dwproductionfeedback[dwjobseriesstep.number_up_exit_1]
		lineageTag: 2c61ba58-8886-4a42-8809-10e029772fb6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quantity Fed' = dwproductionfeedback[quantity_fed_in]
		formatString: 0
		lineageTag: 6b88d6c4-4d9d-4f9a-9615-0e82ef62bf54
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Quantity Produced' = dwproductionfeedback[quantity_produced]
		formatString: 0
		lineageTag: bb67da1b-d518-41c3-9f3b-e32cdf017c65
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Machine ..' = dwproductionfeedback[Machine Name & #]
		lineageTag: 9f1f4cd6-39ff-40a6-9814-1a2ed4d3a40e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Max Number Out' = CALCULATE(MAX(dwproductionorders[Max number out]),RELATEDTABLE(dwproductionorders))
		lineageTag: 82a79074-4793-4d78-96a3-f28798e6a591
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Full Sheets Produced' = If(dwproductionfeedback[Machine Name & #] = "9002 Strapper" || dwproductionfeedback[Machine Name & #] = "7996 Transfer In", dwproductionfeedback[Quantity Produced]/dwproductionfeedback[Max Number Out],BLANK() )
		lineageTag: f0f5f948-b911-40e5-b1dd-0a8603f6f587
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Number In' = IF(dwproductionfeedback[dwjobseriesstep.number_up_entry_1]=dwproductionfeedback[dwjobseriesstep.number_up_exit_1] , dwproductionfeedback[Number out (entry/exit)], IF(dwproductionfeedback[Number out (entry/exit)]<dwproductionfeedback[Max Number Out],dwproductionfeedback[Max Number Out],dwproductionfeedback[dwjobseriesstep.number_up_exit_1]))
		lineageTag: 7be3f7a1-a865-4090-998f-589a3aa6615c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Full Sheets In' = dwproductionfeedback[Quantity Fed]/dwproductionfeedback[Number In]
		lineageTag: 772502e6-31dc-4002-a5c2-0afc1d5297ec
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sheets Out' = If(AND(dwproductionfeedback[Machine_Count]>1,or(dwproductionfeedback[Line Number]="154",dwproductionfeedback[Machine ..]="9002 Strapper")),dwproductionfeedback[Quantity Produced]/dwproductionfeedback[Number In],dwproductionfeedback[Quantity Produced]/dwproductionfeedback[Number out (entry/exit)])
		lineageTag: 29ed265a-2282-4f64-ab81-65b11d4dc5f5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Status'
		dataType: string
		lineageTag: 84f13a4d-7316-4198-ab22-b230d069cfb5
		summarizeBy: none
		sourceColumn: Order Status

		annotation SummarizationSetBy = Automatic

	column 'Job num' = dwproductionfeedback[dwproductionorders.job_number]
		lineageTag: 46c29386-5fb4-483f-912e-b7d8cc82cc1a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Machine' = ```
			If(
			dwproductionfeedback[Line Number] = "130"|| 
			dwproductionfeedback[Line Number] = "133"|| 
			dwproductionfeedback[Line Number] = "131"||
			dwproductionfeedback[Line Number] = "132"||
			dwproductionfeedback[Line Number] = "142"||
			dwproductionfeedback[Line Number] = "144"||
			dwproductionfeedback[Line Number] = "146"||
			dwproductionfeedback[Line Number] = "154",
			
			"Yes",BLANK())
			```
		lineageTag: e8fbac1f-c20f-4f6a-931b-9fe6a7647824
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quantity Fed 2' = If(dwproductionfeedback[Is Machine] = "Yes",dwproductionfeedback[quantity_fed_in]/dwproductionfeedback[Number In],BLANK())
		lineageTag: c88894c0-742c-461d-9298-e15a013aaf4a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Speed' = dwproductionfeedback[Quantity Fed 2]/dwproductionfeedback[Uptime Hours]
		formatString: #,0
		lineageTag: bbcfc610-67a1-4f37-a263-c41e14aef63c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Feedback Start' = RELATED(dwjobseriesstep[feedback_start])
		formatString: General Date
		lineageTag: 31c8d21c-8278-4b92-804a-e39899811d8b
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 29766161-ca8f-4933-84c7-ff8c60163845
			defaultHierarchy: LocalDateTable_dfa2abbc-c8e3-431f-bde5-643e42cdc028.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Setup Start' = RELATED(dwjobseriesstep[setup_started])
		formatString: General Date
		lineageTag: 364a6ebc-561c-4707-9ba3-ec294619ae17
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 7090e617-7381-41b0-98ba-3497a839f56d
			defaultHierarchy: LocalDateTable_90b76d7a-8d10-463e-94e8-9d61ef57e095.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Setup Finished' = RELATED(dwjobseriesstep[setup_finished])
		formatString: General Date
		lineageTag: ee4352f6-4147-4c6d-8c38-365ec1d27a13
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 40fcda14-e2a5-4553-9856-cb3af998bf53
			defaultHierarchy: LocalDateTable_d01757b8-d628-4aa9-b935-a4d06f890f30.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Run Finished' = RELATED(dwjobseriesstep[run_finished])
		formatString: General Date
		lineageTag: 5269b9d3-5e91-4724-a86d-ba032c7e9da1
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 1c3344ba-b5e4-4884-a9ad-d39646c85669
			defaultHierarchy: LocalDateTable_b29ffd10-c8d2-45c7-8a52-559a0deeec2a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Feedback Finished' = RELATED(dwjobseriesstep[feedback_finish])
		formatString: General Date
		lineageTag: eb95ea45-f4db-483f-a291-ccea736332a1
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 30336a2b-d8cf-4534-90bb-a5256b4ff288
			defaultHierarchy: LocalDateTable_ed3cfc95-11a8-42d1-baa3-1ee7affebf8d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Setup Duration' = DATEDIFF(dwproductionfeedback[Setup Start],dwproductionfeedback[Setup Finished],SECOND)
		dataType: double
		lineageTag: 1dfd0a57-404b-4350-a8d2-d4e76071bbc5
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Setup duration (including downtime)' = dwproductionfeedback[setup_duration_seconds]
		formatString: 0
		lineageTag: 238d7d9f-4123-4965-98d8-7c8ce153c5c3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Run Duration' = DATEDIFF(dwproductionfeedback[Setup Finished],dwproductionfeedback[Run Finished],SECOND)
		formatString: 0
		lineageTag: 7197594c-3151-410d-ba53-b1c1dfa3afaf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Run duration (from kiwi)' = dwproductionfeedback[run_duration_seconds]
		formatString: 0
		lineageTag: b75c9582-b3ca-47d8-84af-bcaa7430665a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Order Duration' = DATEDIFF(dwproductionfeedback[Feedback Start],dwproductionfeedback[Feedback Finished],SECOND)
		formatString: 0
		lineageTag: 3595d86e-be6a-4d56-97fc-1ed3395368db
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Sq ft' = dwproductionfeedback[area_exit]/16/12
		formatString: 0
		lineageTag: 2f0f42c7-0cf9-48c0-9061-4323fdc13f4e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Sq ft per machine hour of uptime' = IFERROR(dwproductionfeedback[Sq ft]/(dwproductionfeedback[Order Duration]/60/60),BLANK())
		formatString: 0.00
		lineageTag: 621acb34-ef4b-4cd6-ba3c-90ad95c38be4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Actual Run duration minutes' = dwproductionfeedback[run_duration_minutes]
		formatString: 0
		lineageTag: c42ae2c8-f64a-425f-bf85-f3178161baaf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Width in feet' = dwproductionfeedback[exit_width]/16/12
		lineageTag: 2be541d0-7455-4a13-b0cf-7c79611f3620
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Length in feet' = dwproductionfeedback[exit_length]/16/12
		lineageTag: dc94ccee-eeb1-424c-8592-723be537cc12
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'sq ft per box' = dwproductionfeedback[Width in feet]*dwproductionfeedback[Length in feet]
		lineageTag: 242bfe29-33ed-49ac-9fd4-b5f6996e5724
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'total sq ft' = (dwproductionfeedback[sq ft per box]*dwproductionfeedback[Quantity Produced Adjusted for # of Machines])
		formatString: 0.00
		lineageTag: f58d5e71-aa27-41b8-b231-152b461a69ec
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'width in feet (entry)' = dwproductionfeedback[entry_width]/16/12
		formatString: 0
		lineageTag: a76438e2-c7b3-4c1e-9088-dd7cceffb70f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Length in feet entry' = dwproductionfeedback[entry_length]/16/12
		formatString: 0
		lineageTag: 72d2a71a-b78e-4001-96ba-c4fc676e8d29
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'sq ft per box entry' = dwproductionfeedback[width in feet (entry)]*dwproductionfeedback[Length in feet entry]
		lineageTag: 72abf74a-f761-4ca7-a250-7530dedb816a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'total sq ft entry' = dwproductionfeedback[sq ft per box entry]*dwproductionfeedback[quantity_fed_in]
		lineageTag: 404501fd-d0a0-48f0-b8c5-6eb056ae9e8b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Run_Count = ```
			
			CALCULATE(
			    COUNTROWS(dwproductionfeedback),
			    ALLEXCEPT(dwproductionfeedback, dwproductionfeedback[dwproductionorders.job_number]),
			    dwproductionfeedback[Is Machine] = "Yes"
			)
			
			
			
			
			```
		formatString: 0
		lineageTag: 33e88e78-6779-48fd-94ea-9c92b724643c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Waste Ratio (Evenly Distributed)' = 1/dwproductionfeedback[Run_Count]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8d0db6ed-85eb-42a6-aad8-6bf93ea9f856
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Sheets Produced' = dwproductionfeedback[quantity_produced]/dwproductionfeedback[Number out (entry/exit)]
		lineageTag: c8f8af99-23cc-4f57-a5a7-b406be401af2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Machine_Count = ```
			
			CALCULATE(
			    DISTINCTCOUNT(dwproductionfeedback[Line Number]),
			    ALLEXCEPT(dwproductionfeedback, dwproductionfeedback[dwproductionorders.job_number]),
			    dwproductionfeedback[Is Machine] = "Yes"
			)
			
			```
		formatString: 0
		lineageTag: 4d251035-1698-4d32-8add-645c7ba125a0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Quantity Produced Adjusted for # of Machines' = IFERROR(dwproductionfeedback[quantity produced]/dwproductionfeedback[Machine_Count],BLANK())
		lineageTag: 1200fbd8-1bc3-4fe7-90a6-577706e75621
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'OEE Goal' = RELATED(cr791_lines[OEE Goal])
		lineageTag: fdd66bee-7b8f-40ea-b361-19660be53213
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Line/Spec = CONCATENATE(dwproductionfeedback[Line Number], dwproductionfeedback[dwproductionorders.spec_number])
		lineageTag: 0de34471-3c6c-4aa4-851c-9f8bb5f65bec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Max Line/Spec Speed' = RELATED(DistinctLineSpec[Spec Standard Speed (MaxSpeedBelowOptimum)])
		formatString: 0
		lineageTag: 66e1f665-e131-4d99-9a75-a28b3c7bf3c7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Line/Spec Speed %' = dwproductionfeedback[Max Line/Spec Speed]/dwproductionfeedback[Actual Speed]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ed8bd219-7cbe-4e69-9213-e6d3f5ff6f76
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Speed Above Optimum (T/F)' = IF(dwproductionfeedback[Actual Speed]>dwproductionfeedback[dwcostcenters.optimum_run_speed],TRUE(),FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8c8308f5-0705-44b3-aff7-fa270355c9a5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quality Less Than 10%' = IF(dwproductionfeedback[Quality %%]<.1,TRUE(),FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7933e39e-a9dd-422d-a91c-2cd57ca5e237
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Quality %%' = dwproductionfeedback[Sheets Produced]/(dwproductionfeedback[Sheets Produced]+dwproductionfeedback[rolled up wasted quantity reported])
		formatString: 0.00
		lineageTag: f02a917f-b057-4304-aaae-94c4eb758436
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column feedback_report_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 83af271c-c815-485f-8410-05b59d0338f5
		summarizeBy: none
		sourceColumn: feedback_report_date

		variation Variation
			isDefault
			relationship: 07a4bf61-3a63-4f22-a52c-b25f7f72dc4f
			defaultHierarchy: LocalDateTable_d735e7e6-b238-4221-b290-7d3dc96585d6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column actual_run_duration_hours
		dataType: string
		lineageTag: cb71b955-216a-43ff-a005-8e40a507ad9b
		summarizeBy: none
		sourceColumn: actual_run_duration_hours

		annotation SummarizationSetBy = Automatic

	column 'Sheets Fed Per Hour'
		dataType: string
		lineageTag: 18940d58-e737-4af1-b423-0d0e1e6ac4fc
		summarizeBy: none
		sourceColumn: Sheets Fed Per Hour

		annotation SummarizationSetBy = Automatic

	column 'Speed Above Optimum'
		dataType: string
		lineageTag: e4fbbf52-04f2-4875-8f5c-640259f200ef
		summarizeBy: none
		sourceColumn: Speed Above Optimum

		annotation SummarizationSetBy = Automatic

	column 'June 2025 131'
		dataType: string
		lineageTag: 79c58e84-c89b-48e9-89dd-38328767509a
		summarizeBy: none
		sourceColumn: June 2025 131

		annotation SummarizationSetBy = Automatic

	column 'Final Speed Rating'
		dataType: string
		lineageTag: 0054f935-538e-4fd2-b5cf-456fc04f7e15
		summarizeBy: none
		sourceColumn: Final Speed Rating

		annotation SummarizationSetBy = Automatic

	column 'Downtime Hours' = CALCULATE(SUM(dwjobseriesstep[Total Downtime]),RELATEDTABLE(dwjobseriesstep))
		formatString: 0.00
		lineageTag: 738a04c1-b51b-4d62-96ff-8d61f9566218
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Downtime during setup' = CALCULATE(SUM(dwjobseriesstep[Setup Downtime]),RELATEDTABLE(dwjobseriesstep))
		formatString: 0.00
		lineageTag: 491a952a-4c53-4716-a6f8-5c35cba5bcc9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Run Hours' = (dwproductionfeedback[Order Duration]/60/60) - (dwproductionfeedback[Setup duration (including downtime)]/60/60) - dwproductionfeedback[Downtime during setup]
		formatString: 0.00
		lineageTag: 0cd9dd32-c747-4f89-b01f-ff34154b6973
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Uptime Hours' = dwproductionfeedback[Run Hours] - dwproductionfeedback[Downtime Hours] + dwproductionfeedback[Downtime during setup]
		formatString: 0.00
		lineageTag: ddf9c8a9-378e-4825-b8f1-1bec3df0ce83
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition dwproductionfeedback = m
		mode: import
		source = ```
				let
				    Source = Sql.Databases("192.168.1.12"),
				    kdw_master = Source{[Name="kdw_master"]}[Data],
				    dbo_dwproductionfeedback = kdw_master{[Schema="dbo",Item="dwproductionfeedback"]}[Data],
				    #"Expanded dwcostcenters" = Table.ExpandRecordColumn(dbo_dwproductionfeedback, "dwcostcenters", {"costcenter_number", "costcenter_name", "optimum_run_speed"}, {"dwcostcenters.costcenter_number", "dwcostcenters.costcenter_name", "dwcostcenters.optimum_run_speed"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded dwcostcenters",{"feedback_dataset", "feedback_time_zone"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns", each ([feedback_report_date] <> #date(2022, 8, 21) and [feedback_report_date] <> #date(2022, 8, 22) and [feedback_report_date] <> #date(2022, 8, 23) and [feedback_report_date] <> #date(2022, 8, 24) and [feedback_report_date] <> #date(2022, 8, 25) and [feedback_report_date] <> #date(2022, 8, 26) and [feedback_report_date] <> #date(2022, 8, 29) and [feedback_report_date] <> #date(2022, 8, 30) and [feedback_report_date] <> #date(2022, 8, 31) and [feedback_report_date] <> #date(2022, 9, 1) and [feedback_report_date] <> #date(2022, 9, 2) and [feedback_report_date] <> #date(2022, 9, 6) and [feedback_report_date] <> #date(2022, 9, 7) and [feedback_report_date] <> #date(2022, 9, 8) and [feedback_report_date] <> #date(2022, 9, 9) and [feedback_report_date] <> #date(2022, 9, 10) and [feedback_report_date] <> #date(2022, 9, 12) and [feedback_report_date] <> #date(2022, 9, 13) and [feedback_report_date] <> #date(2022, 9, 14) and [feedback_report_date] <> #date(2022, 9, 15) and [feedback_report_date] <> #date(2022, 9, 16) and [feedback_report_date] <> #date(2022, 9, 19) and [feedback_report_date] <> #date(2022, 9, 20) and [feedback_report_date] <> #date(2022, 9, 21) and [feedback_report_date] <> #date(2022, 9, 22) and [feedback_report_date] <> #date(2022, 9, 23) and [feedback_report_date] <> #date(2022, 9, 24) and [feedback_report_date] <> #date(2022, 9, 26) and [feedback_report_date] <> #date(2022, 9, 27) and [feedback_report_date] <> #date(2022, 9, 28) and [feedback_report_date] <> #date(2022, 9, 29) and [feedback_report_date] <> #date(2022, 9, 30))),
				    #"Expanded dwproductionorders" = Table.ExpandRecordColumn(#"Filtered Rows1", "dwproductionorders", {"production_order_board_grade", "production_order_flute", "production_order_board_density", "production_order_board_paper_density", "production_order_board_thickness", "production_order_board_wall", "production_order_material_class", "spec_number", "job_number", "customer_order_number", "delivery_time", "due_datetime", "date_ordered", "job_status", "difficulty_factor", "production_order_die_number", "product_description", "part_number", "job_description", "date_chg_count", "original_due_date", "old_spec_number", "dwsalesorder"}, {"dwproductionorders.production_order_board_grade", "dwproductionorders.production_order_flute", "dwproductionorders.production_order_board_density", "dwproductionorders.production_order_board_paper_density", "dwproductionorders.production_order_board_thickness", "dwproductionorders.production_order_board_wall", "dwproductionorders.production_order_material_class", "dwproductionorders.spec_number", "dwproductionorders.job_number", "dwproductionorders.customer_order_number", "dwproductionorders.delivery_time", "dwproductionorders.due_datetime", "dwproductionorders.date_ordered", "dwproductionorders.job_status", "dwproductionorders.difficulty_factor", "dwproductionorders.production_order_die_number", "dwproductionorders.product_description", "dwproductionorders.part_number", "dwproductionorders.job_description", "dwproductionorders.date_chg_count", "dwproductionorders.original_due_date", "dwproductionorders.old_spec_number", "dwproductionorders.dwsalesorder"}),
				    #"Expanded dwproductionorders.dwsalesorder" = Table.ExpandTableColumn(#"Expanded dwproductionorders", "dwproductionorders.dwsalesorder", {"sales_order_order_status"}, {"dwproductionorders.dwsalesorder.sales_order_order_status"}),
				    #"Expanded dwjobseriesstep" = Table.ExpandRecordColumn(#"Expanded dwproductionorders.dwsalesorder", "dwjobseriesstep", {"number_up_entry_1", "number_up_exit_1"}, {"dwjobseriesstep.number_up_entry_1", "dwjobseriesstep.number_up_exit_1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded dwjobseriesstep",{{"dwproductionorders.dwsalesorder.sales_order_order_status", "Order Status"}, {"dwcostcenters.costcenter_number", "Line Number"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"feedback_uniq_id", "feedback_csc_order_id", "feedback_pcs_order_id", "feedback_dryend_id", "feedback_program_id", "feedback_calendar_id", "feedback_costcenter_id", "feedback_customer_id", "feedback_customer_address_id", "run_waste_entry", "run_waste_exit", "other_waste", "number_samples", "waste_quantity_reworked", "entry_length_unit", "entry_width_unit", "exit_length_unit", "exit_width_unit", "planned_run_speed_unit", "planned_setup_waste", "planned_run_waste", "planned_post_wait", "feedback_standard_setup_time", "series_priority", "number_of_pallets", "ink_coverage_percentage", "decimal_crew_size", "selling_price", "position_was_in_lineup", "area_entry_unit", "area_exit_unit", "weight_entry_unit", "weight_entry", "weight_exit", "weight_exit_unit", "target_speed_unit", "target_setup_time", "board_total_cost", "board_total_cost_unit", "paper_cost", "paper_cost_unit", "edited_start", "edited_setup", "edited_finish", "edited_ofi_quantity", "edited_quantity_fed", "edited_quantity_produced", "edited_mdc_count", "weight_produced", "weight_produced_unit", "area_produced_unit", "machine_availability", "machine_performance", "machine_quality", "feedback_oee", "target_availability", "target_performance", "target_quality", "target_oee", "oee_variance", "number_of_inks_printed", "mirror_scoring", "job_setup_flag", "num_of_folds", "reported_quantity", "mas_paper_1", "mas_width_1", "mas_paper_2", "mas_width_2", "mas_paper_3", "mas_width_3", "mas_paper_4", "mas_width_4", "mas_paper_5", "mas_width_5", "feedback_count_as_shift_split", "feedback_count_as_setup", "feedback_record_origin", "feedback_record_status", "feedback_record_last_changed", "feedback_board_grade_id", "dwproductionorders.production_order_board_grade", "dwproductionorders.production_order_flute", "dwproductionorders.production_order_board_density", "dwproductionorders.production_order_board_paper_density", "dwproductionorders.production_order_board_thickness", "dwproductionorders.production_order_board_wall", "dwproductionorders.production_order_material_class", "dwproductionorders.customer_order_number", "dwproductionorders.due_datetime", "dwproductionorders.delivery_time", "dwproductionorders.date_ordered", "dwproductionorders.job_status", "dwproductionorders.difficulty_factor", "dwproductionorders.production_order_die_number", "dwproductionorders.product_description", "dwproductionorders.part_number", "dwproductionorders.job_description", "dwproductionorders.date_chg_count", "dwproductionorders.original_due_date", "dwproductionorders.old_spec_number"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Columns1",{{"feedback_report_date", Order.Descending}}),
				    #"Filtered Rows2" = Table.SelectRows(#"Sorted Rows", each ([Line Number] <> 110 and [Line Number] <> 111 and [Line Number] <> 6170) and ([actual_run_duration_minutes] <> 0)),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows2", "actual_run_duration_hours", each [actual_run_duration_seconds]/60/60),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Sheets Fed Per Hour", each [quantity_fed_in]/[actual_run_duration_hours]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Speed Above Optimum", each 
				    if [Line Number] = 154 then
				        if [Sheets Fed Per Hour] > 15000 then "Above Optimum" else "Good"
				    else
				        if [Sheets Fed Per Hour] > [dwcostcenters.optimum_run_speed] then "Above Optimum" else "Good"
				),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "June 2025 131", each if Date.Month([feedback_report_date]) = 6 and Date.Year([feedback_report_date]) = 2025 and [Line Number] = 131 then "Yes" else "No"),
				    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Final Speed Rating", each 
				    if [June 2025 131] = "Yes" then
				        "Good"
				    else
				        [Speed Above Optimum]
				),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom4", each ([Final Speed Rating] = "Good") and ([Line Number] = 130 or [Line Number] = 131 or [Line Number] = 132 or [Line Number] = 133 or [Line Number] = 142 or [Line Number] = 144 or [Line Number] = 146 or [Line Number] = 154))
				in
				    #"Filtered Rows"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

