table dwwaste
	lineageTag: 5b440943-46a4-4789-90d4-c596b306e8d6

	column waste_id
		dataType: int64
		formatString: 0
		lineageTag: 62ff4831-cf68-4bd9-b699-66616dc15c59
		summarizeBy: sum
		sourceColumn: waste_id

		annotation SummarizationSetBy = Automatic

	column job_series_step_id
		dataType: int64
		formatString: 0
		lineageTag: 49311396-50dc-4c96-842e-c621a453f86f
		summarizeBy: none
		sourceColumn: job_series_step_id

		annotation SummarizationSetBy = Automatic

	column alternate_job_series_step_id
		dataType: int64
		formatString: 0
		lineageTag: 0a3e1209-10f0-409c-b829-e5b6f089df34
		summarizeBy: sum
		sourceColumn: alternate_job_series_step_id

		annotation SummarizationSetBy = Automatic

	column waste_calendar_id
		dataType: int64
		formatString: 0
		lineageTag: 931b02f7-1f9a-427d-a6b6-09df6e0b4d65
		summarizeBy: sum
		sourceColumn: waste_calendar_id

		annotation SummarizationSetBy = Automatic

	column waste_date_id
		dataType: int64
		formatString: 0
		lineageTag: ff83731c-8520-4cd7-ae45-cc063c9f06c3
		summarizeBy: sum
		sourceColumn: waste_date_id

		annotation SummarizationSetBy = Automatic

	column waste_costcenter_id
		dataType: int64
		formatString: 0
		lineageTag: c208807b-136d-48a3-9227-9b6882b5a4a7
		summarizeBy: sum
		sourceColumn: waste_costcenter_id

		annotation SummarizationSetBy = Automatic

	column waste_dataset
		dataType: string
		lineageTag: 2d4653b6-9b3a-4c44-bd5d-71a7de9bc09d
		summarizeBy: none
		sourceColumn: waste_dataset

		annotation SummarizationSetBy = Automatic

	column waste_report_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0919bfe4-6629-4277-a720-ae6acd2620c2
		summarizeBy: none
		sourceColumn: waste_report_date

		variation Variation
			isDefault
			relationship: 437c4593-fcfa-4db9-96cd-dfaea5296965
			defaultHierarchy: LocalDateTable_4de40e76-2180-490d-8426-df623bf4b26c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column waste_time_zone
		dataType: string
		lineageTag: f3bfacb2-a997-4abd-ad16-4a7cf4749743
		summarizeBy: none
		sourceColumn: waste_time_zone

		annotation SummarizationSetBy = Automatic

	column waste_code
		dataType: string
		lineageTag: 0c72d042-52b8-482a-872e-b7a1b0126b88
		summarizeBy: none
		sourceColumn: waste_code

		annotation SummarizationSetBy = Automatic

	column wasted_quantity
		dataType: int64
		formatString: 0
		lineageTag: 7d7e59e3-715b-4540-9a74-7fb0644165be
		summarizeBy: sum
		sourceColumn: wasted_quantity

		annotation SummarizationSetBy = Automatic

	column waste_recorded_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 65aaed1e-90ce-42d7-b4fa-437eac031277
		summarizeBy: none
		sourceColumn: waste_recorded_datetime

		variation Variation
			isDefault
			relationship: 4838cdf6-3814-4ddc-b5ba-c5e98c90f747
			defaultHierarchy: LocalDateTable_3d61a67c-890a-4a94-96d9-289b5e08bce6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column waste_scrap_value
		dataType: int64
		formatString: 0
		lineageTag: 7ec37cb2-0c50-4b11-beb3-04fa8b235508
		summarizeBy: sum
		sourceColumn: waste_scrap_value

		annotation SummarizationSetBy = Automatic

	column waste_description
		dataType: string
		lineageTag: 1ebe7bf8-cbf5-477d-b718-6bae18c4e656
		summarizeBy: none
		sourceColumn: waste_description

		annotation SummarizationSetBy = Automatic

	column waste_property
		dataType: int64
		formatString: 0
		lineageTag: a8ac70c8-6efe-4157-adfd-d2f9912c8630
		summarizeBy: sum
		sourceColumn: waste_property

		annotation SummarizationSetBy = Automatic

	column waste_property_description
		dataType: string
		lineageTag: bfb26667-e907-4ab0-9561-6502470d0930
		summarizeBy: none
		sourceColumn: waste_property_description

		annotation SummarizationSetBy = Automatic

	column waste_category
		dataType: int64
		formatString: 0
		lineageTag: 75cdeaec-beed-4113-bcb1-329730569074
		summarizeBy: sum
		sourceColumn: waste_category

		annotation SummarizationSetBy = Automatic

	column waste_category_description
		dataType: string
		lineageTag: d27243aa-32bb-4023-aeec-972ba50da379
		summarizeBy: none
		sourceColumn: waste_category_description

		annotation SummarizationSetBy = Automatic

	column waste_at_previous_process
		dataType: string
		lineageTag: 1b5704e5-9876-47d9-91c2-7ae72ef991b6
		summarizeBy: none
		sourceColumn: waste_at_previous_process

		annotation SummarizationSetBy = Automatic

	column waste_area
		dataType: int64
		formatString: 0
		lineageTag: 42b4bff5-1e86-4078-b96b-7f6266200da0
		summarizeBy: sum
		sourceColumn: waste_area

		annotation SummarizationSetBy = Automatic

	column waste_area_unit
		dataType: string
		lineageTag: 6d391a66-fdad-476a-b891-3921f005640d
		summarizeBy: none
		sourceColumn: waste_area_unit

		annotation SummarizationSetBy = Automatic

	column waste_weight
		dataType: int64
		formatString: 0
		lineageTag: af11d0e8-b9b0-402c-82b5-3ac7f9a3592c
		summarizeBy: sum
		sourceColumn: waste_weight

		annotation SummarizationSetBy = Automatic

	column waste_weight_unit
		dataType: string
		lineageTag: 78730eec-28de-4293-b136-916969a2274f
		summarizeBy: none
		sourceColumn: waste_weight_unit

		annotation SummarizationSetBy = Automatic

	column check_waste_quantity
		dataType: string
		lineageTag: d862dfae-7308-40a5-b268-fb7d7e4c51a6
		summarizeBy: none
		sourceColumn: check_waste_quantity

		annotation SummarizationSetBy = Automatic

	column waste_unique_number
		dataType: int64
		formatString: 0
		lineageTag: 62aac799-dfa0-49e9-8902-f6a760992eb2
		summarizeBy: sum
		sourceColumn: waste_unique_number

		annotation SummarizationSetBy = Automatic

	column waste_record_status
		dataType: string
		lineageTag: 95025297-cda0-4009-be99-12874e098a19
		summarizeBy: none
		sourceColumn: waste_record_status

		annotation SummarizationSetBy = Automatic

	column waste_record_last_changed
		dataType: dateTime
		formatString: General Date
		lineageTag: bfacc763-7131-4e56-b826-22d3720a23ee
		summarizeBy: none
		sourceColumn: waste_record_last_changed

		variation Variation
			isDefault
			relationship: f7b9d8d7-e630-4405-a551-f97ffc762804
			defaultHierarchy: LocalDateTable_0c0faec8-3974-40b4-a7d1-d36bd4639754.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Wasted Quantity' = if(dwwaste[waste_property]=0, blank(),dwwaste[wasted_quantity])
		formatString: 0
		lineageTag: 13b15c32-4c59-4ee9-a852-7fd5bb5c2bbb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Pre Run Waste' = if(dwwaste[waste_property]= 1,dwwaste[wasted_quantity], blank())
		formatString: 0
		lineageTag: e629ac3a-d680-429f-9d70-6f1c30d69c12
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition dwwaste = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.1.12"),
				    kdw_master = Source{[Name="kdw_master"]}[Data],
				    dbo_dwwaste = kdw_master{[Schema="dbo",Item="dwwaste"]}[Data],
				    #"Sorted Rows" = Table.Sort(dbo_dwwaste,{{"waste_id", Order.Descending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each ([waste_id] <> 46911 and [waste_id] <> 47010))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

