table RIG
	lineageTag: 7bcb72b3-7c06-4fe9-8346-75c3bd27968e

	column 'R.I.G. Intro'
		dataType: string
		lineageTag: 5a61a6ba-7107-422a-80c9-bec295ad835a
		summarizeBy: none
		sourceColumn: R.I.G. Intro

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: string
		lineageTag: 99523fbc-4d6d-4423-a85b-c9e170de9524
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition RIG = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://jetcontainercompany.sharepoint.com/sites/ContinuousImprovement/Shared%20Documents/General/Employee%20of%20the%20Month,%20COGs,%20Upcoming%20Shutdowns.xlsx"), null, true),
				    RIG_Table = Source{[Item="RIG",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(RIG_Table,{{"R.I.G. Intro", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

