table espInvoice
	lineageTag: 02bfd332-8bc5-490d-a64e-3992341bcd7e

	column ID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: a647b79a-7d9d-4717-91da-9ec7d7d5e6e3
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column mainttime
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 3c9b4bf3-fcb9-4a15-884d-218de0b270bb
		summarizeBy: none
		sourceColumn: mainttime

		variation Variation
			isDefault
			relationship: ef2acd0f-382b-4529-8ff9-d02f44f5319d
			defaultHierarchy: LocalDateTable_799227bf-a5d1-4b19-8fe2-43b3bf3ae3fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column userID
		dataType: string
		displayFolder: IDs
		lineageTag: 0191499c-fddf-4c34-b56f-f60af868baed
		summarizeBy: none
		sourceColumn: userID

		annotation SummarizationSetBy = Automatic

	column invoicenumber
		dataType: string
		lineageTag: 21bf33e6-95f3-40bc-9775-733d0946140e
		summarizeBy: none
		sourceColumn: invoicenumber

		annotation SummarizationSetBy = Automatic

	column transactiondate
		dataType: dateTime
		formatString: Short Date
		displayFolder: Dates
		lineageTag: da3b48cd-1a9c-4650-97ee-1cfc58083a3a
		summarizeBy: none
		sourceColumn: transactiondate

		variation Variation
			isDefault
			relationship: 69ee1bb3-a109-4c2e-984a-210097e7b410
			defaultHierarchy: LocalDateTable_d4de1993-98a4-4aa2-8e8b-3c50fee2b8a4.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column goodsvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 35b4d27e-4d02-4e64-92b3-833a6dd15ee2
		summarizeBy: sum
		sourceColumn: goodsvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column discountvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b25a5b39-c3a0-4f59-9462-6f0f75d7f391
		summarizeBy: sum
		sourceColumn: discountvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column salestax1
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Extra
		lineageTag: 8b7ab08d-968d-4487-a0f5-82390836bd4a
		summarizeBy: sum
		sourceColumn: salestax1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column salestax2
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Extra
		lineageTag: ce63dc2e-c254-43a7-9941-5a6b643395a4
		summarizeBy: sum
		sourceColumn: salestax2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column salestax3
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Extra
		lineageTag: 579a93de-6b96-4711-866d-247e80f5f451
		summarizeBy: sum
		sourceColumn: salestax3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column totalsalestax
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4e22a3aa-6eb0-49aa-bca7-73e785fa2487
		summarizeBy: sum
		sourceColumn: totalsalestax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column freightvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 14bd02ab-72ff-4d9c-9784-4a7e3ddc1ace
		summarizeBy: sum
		sourceColumn: freightvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column palletvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 34bcaee8-9ea9-472c-8330-a0df763a0f20
		summarizeBy: sum
		sourceColumn: palletvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column additionalchargesvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 34039fc7-056e-49c0-b60a-628ed92d44cb
		summarizeBy: sum
		sourceColumn: additionalchargesvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column grosstotalvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 91c94b76-4756-4c6e-b1cc-afa807444837
		summarizeBy: sum
		sourceColumn: grosstotalvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column totalvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e38179df-a82a-44a5-86a6-553b842ad5fc
		summarizeBy: sum
		sourceColumn: totalvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column foreigngoodsvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unused Values
		lineageTag: 78ed4690-92ab-4748-a3d2-a29b175863e3
		summarizeBy: sum
		sourceColumn: foreigngoodsvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column foreignfreightvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unused Values
		lineageTag: 6a2ade13-0e8c-4939-a314-30b24c4b14b8
		summarizeBy: sum
		sourceColumn: foreignfreightvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column foreignpalletvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unused Values
		lineageTag: 65c695f3-98fe-4fb5-bd99-6507b416e4ad
		summarizeBy: sum
		sourceColumn: foreignpalletvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column foreignadditionalchargesvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unused Values
		lineageTag: 765f91a2-4f42-4b01-bd5f-597140f569af
		summarizeBy: sum
		sourceColumn: foreignadditionalchargesvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column grosstotalforeignvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b3591e2b-5ddd-42a7-8e2c-6752a2939c42
		summarizeBy: sum
		sourceColumn: grosstotalforeignvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column totalforeignvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 46ecb44d-532b-43cc-b653-6031fc7b90f2
		summarizeBy: sum
		sourceColumn: totalforeignvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column foreigndiscount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unused Values
		lineageTag: 3b07bcf6-b444-432e-8082-82f809786629
		summarizeBy: sum
		sourceColumn: foreigndiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column foreignsettlementdiscount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unused Values
		lineageTag: 33098526-2a62-4d25-859d-beeead334523
		summarizeBy: sum
		sourceColumn: foreignsettlementdiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column settlementdiscount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c261c946-8364-42de-9f47-728ee9166830
		summarizeBy: sum
		sourceColumn: settlementdiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column transferreddate
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 317ae8e7-34e2-4115-8d2c-24ef1605c341
		summarizeBy: none
		sourceColumn: transferreddate

		variation Variation
			isDefault
			relationship: 9965d736-548a-47bd-9074-65a649ba0a8e
			defaultHierarchy: LocalDateTable_a4614520-3c26-493f-a56a-8c8e0ebc8dad.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column invoicetype
		dataType: int64
		formatString: 0
		lineageTag: 781a9620-4954-452f-9f60-0c97fe32897e
		summarizeBy: sum
		sourceColumn: invoicetype

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: 524dea0b-5a07-435f-a25b-5dffb4a5b4b1
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column usernumiv01
		dataType: double
		displayFolder: Extra
		lineageTag: 9153fac6-6904-47f5-9d65-33daf9d8a75e
		summarizeBy: sum
		sourceColumn: usernumiv01

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv02
		dataType: double
		displayFolder: Extra
		lineageTag: 1050bed8-c4ae-4fe5-bd88-07618882439c
		summarizeBy: sum
		sourceColumn: usernumiv02

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv03
		dataType: double
		displayFolder: Extra
		lineageTag: dcf54f78-f8dd-4af5-8f35-845989670e60
		summarizeBy: sum
		sourceColumn: usernumiv03

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv04
		dataType: double
		displayFolder: Extra
		lineageTag: e57c928b-6606-4964-a04e-e3b49cfa2af9
		summarizeBy: sum
		sourceColumn: usernumiv04

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv05
		dataType: double
		displayFolder: Extra
		lineageTag: 7bcf01f2-4379-491c-abb2-4c2f1f49f0c4
		summarizeBy: sum
		sourceColumn: usernumiv05

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usercodeiv01
		dataType: string
		displayFolder: Extra
		lineageTag: f9f77671-a5a0-4312-ba59-1a73d0d7b8ca
		summarizeBy: none
		sourceColumn: usercodeiv01

		annotation SummarizationSetBy = Automatic

	column usercodeiv02
		dataType: string
		displayFolder: Extra
		lineageTag: fa1b97f5-1505-48d6-9513-daf311571dbc
		summarizeBy: none
		sourceColumn: usercodeiv02

		annotation SummarizationSetBy = Automatic

	column usercodeiv03
		dataType: string
		displayFolder: Extra
		lineageTag: 149fd118-aa51-4b13-a3b1-386deefe8441
		summarizeBy: none
		sourceColumn: usercodeiv03

		annotation SummarizationSetBy = Automatic

	column usercodeiv04
		dataType: string
		displayFolder: Extra
		lineageTag: abbe4548-3bcd-445e-8a55-a40be7c50e53
		summarizeBy: none
		sourceColumn: usercodeiv04

		annotation SummarizationSetBy = Automatic

	column usercodeiv05
		dataType: string
		displayFolder: Extra
		lineageTag: 5c93a7bd-0889-4961-907c-d79cd09a0981
		summarizeBy: none
		sourceColumn: usercodeiv05

		annotation SummarizationSetBy = Automatic

	column settlementdays
		dataType: int64
		formatString: 0
		lineageTag: 074f60ea-f8ac-4ba0-bb31-9ca5baa097ca
		summarizeBy: sum
		sourceColumn: settlementdays

		annotation SummarizationSetBy = Automatic

	column creditReason
		dataType: string
		lineageTag: 6af823ae-a7df-4574-8a20-73ec0b3707f1
		summarizeBy: none
		sourceColumn: creditReason

		annotation SummarizationSetBy = Automatic

	column terms
		dataType: string
		lineageTag: c92e20ed-59f0-4ad9-86e0-0ac7eb2a7d56
		summarizeBy: none
		sourceColumn: terms

		annotation SummarizationSetBy = Automatic

	column addressID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: b0b4c57a-675d-4df4-9102-28367c838529
		summarizeBy: count
		sourceColumn: addressID

		annotation SummarizationSetBy = Automatic

	column companyID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: a19c4843-da76-4b9c-8b78-3702a642b371
		summarizeBy: count
		sourceColumn: companyID

		annotation SummarizationSetBy = Automatic

	column customerIssueID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: 694adc2d-ffbc-4adc-9f5d-620369e2f2b3
		summarizeBy: count
		sourceColumn: customerIssueID

		annotation SummarizationSetBy = Automatic

	column docketID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: 045cafd7-e7b6-4100-84ac-9a3ad7d65db9
		summarizeBy: count
		sourceColumn: docketID

		annotation SummarizationSetBy = Automatic

	column exchangeRateID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: 5ce9386a-3bf4-4cac-8373-204667192c3a
		summarizeBy: count
		sourceColumn: exchangeRateID

		annotation SummarizationSetBy = Automatic

	column plantID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: 63fb7a1d-1baa-4d91-b97f-8edfbc882b21
		summarizeBy: count
		sourceColumn: plantID

		annotation SummarizationSetBy = Automatic

	column originalInvoiceID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: d946f568-eb7a-4453-acfa-b32432b30ae7
		summarizeBy: count
		sourceColumn: originalInvoiceID

		annotation SummarizationSetBy = Automatic

	column sales1TaxRateID
		dataType: int64
		formatString: 0
		displayFolder: Extra
		lineageTag: bdb4cca7-de9a-4e59-9ea0-dd2626f8a88a
		summarizeBy: count
		sourceColumn: sales1TaxRateID

		annotation SummarizationSetBy = Automatic

	column sales2TaxRateID
		dataType: int64
		formatString: 0
		displayFolder: Extra
		lineageTag: f562aa18-f745-4dfd-97d0-17da34c2ac9c
		summarizeBy: count
		sourceColumn: sales2TaxRateID

		annotation SummarizationSetBy = Automatic

	column sales3TaxRateID
		dataType: int64
		formatString: 0
		displayFolder: Extra
		lineageTag: 8bb2bb6a-690e-4f26-b73e-a5fd3e5919cb
		summarizeBy: count
		sourceColumn: sales3TaxRateID

		annotation SummarizationSetBy = Automatic

	column invoicestatus
		dataType: string
		lineageTag: 347124d1-0a22-45ee-8073-8c38df7c6202
		summarizeBy: none
		sourceColumn: invoicestatus

		annotation SummarizationSetBy = Automatic

	column settlementdate
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 643173f8-e506-46ee-b94b-0f922de8b4f2
		summarizeBy: none
		sourceColumn: settlementdate

		variation Variation
			isDefault
			relationship: 478ac7db-28fb-422f-a247-3fc877744c37
			defaultHierarchy: LocalDateTable_270b6af8-abd5-43a8-a78c-496d9494d494.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ismanual
		dataType: int64
		formatString: 0
		lineageTag: 6b835556-e014-4521-8aea-7cd256708cb9
		summarizeBy: sum
		sourceColumn: ismanual

		annotation SummarizationSetBy = Automatic

	column shiptoAddressID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: a5f2f43a-4efa-4df8-9906-a3e2f11a4189
		summarizeBy: count
		sourceColumn: shiptoAddressID

		annotation SummarizationSetBy = Automatic

	column financialperiodID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: b5d06073-ab35-4f47-a3b6-887c33ec61d3
		summarizeBy: count
		sourceColumn: financialperiodID

		annotation SummarizationSetBy = Automatic

	column settlementDiscountPercent
		dataType: double
		lineageTag: f66bacf7-8b6a-4c6c-9232-b24036aae9ba
		summarizeBy: sum
		sourceColumn: settlementDiscountPercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column totallevyvalue
		dataType: double
		lineageTag: 9fa53237-596e-4384-a866-27da5769ec24
		summarizeBy: sum
		sourceColumn: totallevyvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column createdby
		dataType: string
		lineageTag: 165a5da9-e73d-44ea-8617-44643ac6d916
		summarizeBy: none
		sourceColumn: createdby

		annotation SummarizationSetBy = Automatic

	column usernumiv06
		dataType: double
		displayFolder: Extra
		lineageTag: 0c166e40-95e4-433f-92ca-030994efdba6
		summarizeBy: sum
		sourceColumn: usernumiv06

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv07
		dataType: double
		displayFolder: Extra
		lineageTag: ff977b27-449a-41dc-a4b8-586423025d45
		summarizeBy: sum
		sourceColumn: usernumiv07

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv08
		dataType: double
		displayFolder: Extra
		lineageTag: 6d0839e0-f9b7-41ec-a363-96c033396ea7
		summarizeBy: sum
		sourceColumn: usernumiv08

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv09
		dataType: double
		displayFolder: Extra
		lineageTag: dd5ca525-d073-473a-8e92-6870eb324d66
		summarizeBy: sum
		sourceColumn: usernumiv09

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv10
		dataType: double
		displayFolder: Extra
		lineageTag: dfb861bf-b90e-4ecd-ba00-bedacc9227cc
		summarizeBy: sum
		sourceColumn: usernumiv10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv11
		dataType: double
		displayFolder: Extra
		lineageTag: 18d7e06e-b2ef-462b-a18f-0757473a5c41
		summarizeBy: sum
		sourceColumn: usernumiv11

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usernumiv12
		dataType: double
		displayFolder: Extra
		lineageTag: 4a82b4d7-5e33-4cb9-81de-c1eeb425b9ef
		summarizeBy: sum
		sourceColumn: usernumiv12

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column usercodeiv06
		dataType: string
		displayFolder: Extra
		lineageTag: 7f3df5fe-6c44-43de-98f9-7bca9c810880
		summarizeBy: none
		sourceColumn: usercodeiv06

		annotation SummarizationSetBy = Automatic

	column usercodeiv07
		dataType: string
		displayFolder: Extra
		lineageTag: b3dc8a23-c84b-43f1-9886-5bf45a4e30b0
		summarizeBy: none
		sourceColumn: usercodeiv07

		annotation SummarizationSetBy = Automatic

	column usercodeiv08
		dataType: string
		displayFolder: Extra
		lineageTag: 16efd79f-211d-402d-b090-22ae48731cfb
		summarizeBy: none
		sourceColumn: usercodeiv08

		annotation SummarizationSetBy = Automatic

	column usercodeiv09
		dataType: string
		displayFolder: Extra
		lineageTag: 4b2c8c10-d3d9-4f50-9af2-a663eb2ea9c6
		summarizeBy: none
		sourceColumn: usercodeiv09

		annotation SummarizationSetBy = Automatic

	column usercodeiv10
		dataType: string
		displayFolder: Extra
		lineageTag: 64ea2fbc-bba1-4ee1-b1d2-d1dbe2eb4777
		summarizeBy: none
		sourceColumn: usercodeiv10

		annotation SummarizationSetBy = Automatic

	column usercodeiv11
		dataType: string
		displayFolder: Extra
		lineageTag: 5717d1d6-aefe-4d45-a897-e307f69568b0
		summarizeBy: none
		sourceColumn: usercodeiv11

		annotation SummarizationSetBy = Automatic

	column usercodeiv12
		dataType: string
		displayFolder: Extra
		lineageTag: 7cff5fbc-e117-4b0a-9aa6-bb9dfc1901f9
		summarizeBy: none
		sourceColumn: usercodeiv12

		annotation SummarizationSetBy = Automatic

	column numberoftimessenttoKDG
		dataType: int64
		formatString: 0
		lineageTag: 5e7e135b-cfde-44ae-ac64-c7218acbd188
		summarizeBy: sum
		sourceColumn: numberoftimessenttoKDG

		annotation SummarizationSetBy = Automatic

	column isheld
		dataType: int64
		formatString: 0
		lineageTag: af69a71a-b739-4a95-8732-7fee738feca0
		summarizeBy: sum
		sourceColumn: isheld

		annotation SummarizationSetBy = Automatic

	column isposted
		dataType: int64
		formatString: 0
		lineageTag: 9c1cf9c7-def3-4bd5-8784-a1af6646384e
		summarizeBy: sum
		sourceColumn: isposted

		annotation SummarizationSetBy = Automatic

	column createddate
		dataType: dateTime
		formatString: General Date
		displayFolder: Dates
		lineageTag: 10238986-c312-4079-bda8-5ea1be6b6837
		summarizeBy: none
		sourceColumn: createddate

		variation Variation
			isDefault
			relationship: 98872228-ada9-402d-8049-ac99681ad714
			defaultHierarchy: LocalDateTable_b247cc3e-1511-4444-9dfe-94f1c6cfaf09.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column sales4TaxRateID
		dataType: int64
		formatString: 0
		displayFolder: Extra
		lineageTag: 212046c4-25e8-4da0-bfa6-1d7052be7c04
		summarizeBy: count
		sourceColumn: sales4TaxRateID

		annotation SummarizationSetBy = Automatic

	column sales5TaxRateID
		dataType: int64
		formatString: 0
		displayFolder: Extra
		lineageTag: 02b0000e-3cc7-496a-8890-0febd1c56d20
		summarizeBy: count
		sourceColumn: sales5TaxRateID

		annotation SummarizationSetBy = Automatic

	column sales6TaxRateID
		dataType: int64
		formatString: 0
		displayFolder: Extra
		lineageTag: d21a9aab-efb8-4cc7-a6dc-1472eed47950
		summarizeBy: count
		sourceColumn: sales6TaxRateID

		annotation SummarizationSetBy = Automatic

	column salestax4
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Extra
		lineageTag: fb78e89c-2c35-4999-a536-3ee307696204
		summarizeBy: sum
		sourceColumn: salestax4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column salestax5
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Extra
		lineageTag: 33d35eff-b309-4d46-94a8-416e1416c766
		summarizeBy: sum
		sourceColumn: salestax5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column salestax6
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Extra
		lineageTag: 93aefc7b-c53c-42da-beb0-ae9570d02417
		summarizeBy: sum
		sourceColumn: salestax6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column isImported
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2f11a7dd-2a4a-4292-8d97-c78f6c99daa5
		summarizeBy: none
		sourceColumn: isImported

		annotation SummarizationSetBy = Automatic

	column 'gross total - additional charges' = espInvoice[grosstotalvalue]-espInvoice[additionalchargesvalue]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: .Custom Columns
		lineageTag: 90d11fb8-685f-4932-8c31-0b9af526e662
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Sales Rep' = RELATED(orgCompany[Column 2])
		displayFolder: .Custom Columns
		lineageTag: ccd12b84-056a-410c-9074-23e4472a9e42
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Week Start Date' = espInvoice[transactiondate]-WEEKDAY(espInvoice[transactiondate],2)+1
		formatString: Short Date
		displayFolder: .Custom Columns
		lineageTag: f0142882-726a-4b69-9eb6-6b6bab00d646
		summarizeBy: none

		variation Variation
			isDefault
			relationship: dd9b37c7-7b31-4a1c-bd45-076ccf84586c
			defaultHierarchy: LocalDateTable_487a92d3-604f-40c9-87c4-bb65c0b8865c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Join ID' = espInvoice[Week Start Date].[Date] & " " & espInvoice[companyID]
		lineageTag: d05b85a2-1f01-45b2-97b9-041df0dde669
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Total Area Invoiced' = CALCULATE(SUM(espInvoiceLine[areainvoiced]),RELATEDTABLE(espInvoiceLine))
		displayFolder: .Custom Columns
		lineageTag: 32384e14-6e02-4af2-9e51-090a49cb84b9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'orgCompany.name'
		dataType: string
		lineageTag: 5a967e2a-77b4-4bb4-998c-a4fe1436c2a6
		summarizeBy: none
		sourceColumn: orgCompany.name

		annotation SummarizationSetBy = Automatic

	column 'Total value from invoice lines' = CALCULATE(SUM(espInvoiceLine[Total Sales]),RELATEDTABLE(espInvoiceLine))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5f092ae5-a31b-42ba-b2c9-f3a3c37ec902
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Year = YEAR(espInvoice[transactiondate])
		formatString: 0
		displayFolder: Custom Dates
		lineageTag: 00b41abf-80f7-427b-b34d-38fbdd10dc68
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Month = espInvoice[transactiondate].[Month]
		displayFolder: Custom Dates
		lineageTag: d1935b71-c906-4385-b592-0258eec5ddee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date = CALCULATE(MAX(dwdate[date]),RELATEDTABLE(dwdate))
		formatString: Short Date
		displayFolder: Custom Dates
		lineageTag: 88ff82d1-701a-4db6-902e-58e35396df2a
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 248899a8-23ca-4d77-b38b-f0013a480191
			defaultHierarchy: LocalDateTable_ac9f0b80-abf2-4d5c-8442-48f0c0e61e8e.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'transactiondate - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7539ff31-dcfb-4c80-9b97-8552b09214fa
		summarizeBy: none
		sourceColumn: transactiondate - Copy

		variation Variation
			isDefault
			relationship: 76fb667c-c580-4f3a-8abf-636af665600e
			defaultHierarchy: LocalDateTable_ceb10b7d-5f5a-4d54-b444-6efa4056b66e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Month Date' = EOMONTH(espInvoice[transactiondate - Copy],0)
		formatString: General Date
		lineageTag: a575a660-2af1-4fb4-9233-a34dd4a39487
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 1a5e0447-1446-4ed3-92b8-9ce8995e5c21
			defaultHierarchy: LocalDateTable_03876c76-cb1e-4059-8117-535c185b9edc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Start of month date' = STARTOFMONTH(espInvoice[transactiondate - Copy])
		formatString: General Date
		lineageTag: 676e534c-fd55-4c5e-b1d6-5503a28fc5d3
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 4aa73437-bdd4-4b6f-b824-b40df8f0c4a9
			defaultHierarchy: LocalDateTable_527cfcdf-a2b9-4e67-a404-a92a9a151a1e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Network Days' = NETWORKDAYS(espInvoice[Start of month date],espInvoice[End of Month Date],1,cr60f_holidays)
		formatString: 0
		lineageTag: 03ced094-724d-4781-95dd-f5abc801867c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month unique' = espInvoice[Year] & " " & espInvoice[Month]
		lineageTag: 5c26b311-decf-4e12-be99-77b6af4e654b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First of Month' = DATE(YEAR(espInvoice[transactiondate]),MONTH(espInvoice[transactiondate]),1)
		formatString: Short Date
		lineageTag: 053dd256-860c-4f00-b0ab-696b3175d59d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: d9d8d9a3-429d-4317-8c22-8425e31a5f7e
			defaultHierarchy: LocalDateTable_6f40ae71-5cb0-408a-8793-aa5239f9978e.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Monday = espInvoice[transactiondate - Copy] - WEEKDAY(espInvoice[transactiondate - Copy])+2
		formatString: Short Date
		lineageTag: 09bf1836-697c-4448-9413-9958591e0d15
		summarizeBy: none

		variation Variation
			isDefault
			relationship: ea44eaf9-7326-49ae-be8b-e985a9deba7c
			defaultHierarchy: LocalDateTable_17d12c67-fe87-482f-b94f-60a1329fabf4.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Friday = espInvoice[Monday]+4
		formatString: Short Date
		lineageTag: 7a41f1a5-75dc-44e5-8183-f349a8b263da
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 8a29ecd5-9e42-4655-9e94-8dccf41b5890
			defaultHierarchy: LocalDateTable_f475ee7c-1811-46dc-b6d8-0703fe090a36.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number' = MONTH(espInvoice[transactiondate - Copy])
		formatString: 0
		lineageTag: 43b91a62-f3cb-414f-be37-28fc3f03a93f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Seasonality Multiplier' = ```
			
			LOOKUPVALUE(
			    'Seasonality Summary'[Seasonality Multiplier], 
			    'Seasonality Summary'[Month Number], 
			    espInvoice[Month Number]
			)
			
			```
		formatString: 0.00
		lineageTag: 8c5490d3-a4d8-4f7c-8564-5748a729d2ae
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Projected Sales' = espInvoice[gross total - additional charges]/espInvoice[Seasonality Multiplier]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c4d2d5ac-5abe-4092-83b2-4d827685e735
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Budget Identifier' = espInvoice[Start of month date] & " " & espInvoice[Sales Rep]
		lineageTag: 6625a062-d54d-40dd-816f-338ce0cec16d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Cost = CALCULATE(SUM(espOrder[Cost]),RELATEDTABLE(espInvoiceLine))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: cc163140-f739-42fd-a88c-5ff1a0c51ef4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	hierarchy 'Week Start Date Hierarchy'
		lineageTag: b24162d0-2db4-4e51-b6e9-95ecedfd09d6

		level 'Week Start Date'
			lineageTag: bc484b3b-c0b0-4d97-b859-4ca4dff18b7c
			column: 'Week Start Date'

	partition espInvoice = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.1.12"),
				    esp = Source{[Name="esp"]}[Data],
				    dbo_espInvoice = esp{[Schema="dbo",Item="espInvoice"]}[Data],
				    #"Expanded orgCompany" = Table.ExpandRecordColumn(dbo_espInvoice, "orgCompany", {"name"}, {"orgCompany.name"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Expanded orgCompany", "transactiondate", "transactiondate - Copy"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Duplicated Column",{{"transactiondate - Copy", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

