table espInvoiceLine
	lineageTag: 2ca2a967-a59e-4bfe-9de4-ce3229966957

	column ID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: 7f803239-b5d9-4e24-a393-af50a65c37c7
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		lineageTag: e34e6053-00a3-415f-b6ec-f7af2d78ce17
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column totalvalue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bdeeea34-ea82-44e4-bdf4-6250d990586a
		summarizeBy: sum
		sourceColumn: totalvalue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column areainvoiced
		dataType: double
		lineageTag: e72f9667-863a-4a27-870e-3659ada5a821
		summarizeBy: sum
		sourceColumn: areainvoiced

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weightinvoiced
		dataType: double
		lineageTag: 338c02ed-042b-4365-ab87-821603a21d45
		summarizeBy: sum
		sourceColumn: weightinvoiced

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column invoiceLineType
		dataType: string
		lineageTag: cdf1ef99-9d86-4a2d-86b2-f6ecd3027e64
		summarizeBy: none
		sourceColumn: invoiceLineType

		annotation SummarizationSetBy = Automatic

	column docketItemID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: e24e8c7d-b071-40b8-b592-7d70b521fa67
		summarizeBy: count
		sourceColumn: docketItemID

		annotation SummarizationSetBy = Automatic

	column invoiceID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: f5ad34b4-e30e-4a72-b1e6-18ebabcab9e8
		summarizeBy: none
		sourceColumn: invoiceID

		annotation SummarizationSetBy = Automatic

	column orderID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: e642b489-fae7-4168-97b2-19f0cc7930e4
		summarizeBy: count
		sourceColumn: orderID

		annotation SummarizationSetBy = Automatic

	column originalInvoiceLineID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: 92576c72-4f6c-4a55-87c1-3500b9ad31ad
		summarizeBy: count
		sourceColumn: originalInvoiceLineID

		annotation SummarizationSetBy = Automatic

	column tradediscountpercent
		dataType: double
		lineageTag: 7a665ed3-6ae4-4443-8c4f-32e0c69066ed
		summarizeBy: sum
		sourceColumn: tradediscountpercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column parentInvoiceLineID
		dataType: int64
		formatString: 0
		displayFolder: IDs
		lineageTag: 740d393c-cece-4576-b5e9-bc01e913cdf7
		summarizeBy: count
		sourceColumn: parentInvoiceLineID

		annotation SummarizationSetBy = Automatic

	column invoicelinemode
		dataType: int64
		formatString: 0
		lineageTag: ab351597-eb70-4548-9905-e27ef47f13f5
		summarizeBy: sum
		sourceColumn: invoicelinemode

		annotation SummarizationSetBy = Automatic

	column 'Total Quantity' = SUMX(FILTER(espInvoiceLine,espInvoiceLine[Job Number] = EARLIER(espInvoiceLine[Job Number])),espInvoiceLine[quantity])
		lineageTag: eb9b2f07-162f-437f-b1c5-f7d2c12df6f0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Sales' = If(espInvoiceLine[invoiceLineType] = "Additional Charge", blank(), espInvoiceLine[totalvalue])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 10361514-d01d-4ab6-81ff-a150b0981eda
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'transaction date' = espInvoiceLine[espInvoice.transactiondate]
		formatString: Short Date
		lineageTag: 888c857a-80cb-419a-8064-3398eb41ceba
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e27b0e65-6e5f-4b04-a39f-b86ad0d2c677
			defaultHierarchy: LocalDateTable_8b82cc39-d863-466f-80e8-3f28b65048b0.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'espOrder.jobnumber'
		dataType: string
		lineageTag: 934b6d89-57ff-4594-9894-2e500133840d
		summarizeBy: none
		sourceColumn: espOrder.jobnumber

		annotation SummarizationSetBy = Automatic

	column 'espOrder.freight'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 115d61b8-475d-4036-856c-cc31067463dd
		summarizeBy: sum
		sourceColumn: espOrder.freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'espInvoice.transactiondate'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9189bee-e9cf-4eaa-bcb2-f1466e7f0012
		summarizeBy: none
		sourceColumn: espInvoice.transactiondate

		variation Variation
			isDefault
			relationship: ba35608b-9041-4fae-8109-74547a4a7027
			defaultHierarchy: LocalDateTable_1c643909-ccef-4192-858e-24d7e7a7f923.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'espOrder.cstCostEstimate(precostestimateID).ID'
		dataType: int64
		formatString: 0
		lineageTag: 377898f4-ff73-4b3b-83ef-48377d5ed7cb
		summarizeBy: none
		sourceColumn: espOrder.cstCostEstimate(precostestimateID).ID

		annotation SummarizationSetBy = Automatic

	column 'Number of Similar Rows' = ```
			
			CALCULATE(
			    COUNTROWS(espInvoiceLine),
			    FILTER(
			        espInvoiceLine,
			        espInvoiceLine[Month Year] = EARLIER(espInvoiceLine[Month Year])
			    )
			)
			
			```
		formatString: 0
		lineageTag: dab0f96e-bc65-4558-a918-9aa524122623
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Calculated quantity' = RELATED(cstCostEstimate[calculationquantity])/espInvoiceLine[Number of Similar Rows]
		lineageTag: 333cd189-90fd-40e1-8a52-396a5c8c810a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quantity Mulitplier' = espInvoiceLine[Calculated quantity]/1000
		lineageTag: 5eb6c2dd-d53b-49ba-94b6-caa60533928c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimated Full Cost' = RELATED(cstCostEstimate[fullcost])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 10ead496-1f5d-4ab1-89db-790aa5167b20
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Job Number' = RELATED(espOrder[jobnumber])
		lineageTag: ff1f15d5-3f49-4327-8c30-922d46521738
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Column = espInvoiceLine[totalvalue]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8a5de669-4e0c-432d-a70f-c7a64accbaaf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Estimated cost' = (espInvoiceLine[quantity]/1000)*espInvoiceLine[Estimated Full Cost]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f291cb07-e973-4b6d-b58f-7bebbabfffd6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Month = MONTH(espInvoiceLine[transaction date])
		formatString: 0
		lineageTag: fd793fba-9621-429c-b807-28486e454d6d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Year = YEAR(espInvoiceLine[transaction date])
		formatString: 0
		lineageTag: 80ca3204-ccbb-4bdf-add2-be370e404b75
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Month Year' = espInvoiceLine[Month] & " " & espInvoiceLine[Year]
		lineageTag: 854b2d19-90b2-4831-8a93-4d177592946b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Sales Last Year Same Month' = ```
			
			VAR CurrentYear = YEAR(espInvoiceLine[transaction date])
			VAR CurrentMonth = MONTH(espInvoiceLine[transaction date])
			VAR PreviousYearSales = CALCULATE(
			    SUM(espInvoiceLine[Total Sales]),
			    FILTER(
			        ALL(espInvoiceLine),
			        YEAR(espInvoiceLine[transaction date]) = CurrentYear - 1 &&
			        MONTH(espInvoiceLine[transaction date]) = CurrentMonth
			    )
			)
			RETURN
			PreviousYearSales
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 123ea0e0-48cb-4087-a878-b10645ef3ff0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Last Years Sales' = espInvoiceLine[Sales Last Year Same Month]/espInvoiceLine[Number of Similar Rows]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6c348454-ceee-497d-a609-5abc16dd8d99
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Contribution $ Last Year Same Month' =
			
			VAR CurrentYear = YEAR(espInvoiceLine[transaction date])
			VAR CurrentMonth = MONTH(espInvoiceLine[transaction date])
			VAR PreviousYearSales = CALCULATE(
			    SUM(espInvoiceLine[Contribution $]),
			    FILTER(
			        ALL(espInvoiceLine),
			        YEAR(espInvoiceLine[transaction date]) = CurrentYear - 1 &&
			        MONTH(espInvoiceLine[transaction date]) = CurrentMonth
			    )
			)
			RETURN
			PreviousYearSales
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a6a25fed-01b1-4717-bdcf-577fd6bf3259
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Contribution $' = espInvoiceLine[Total Sales] - espInvoiceLine[Estimated cost]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 32ad331d-9fe0-47f3-baba-1aabd11fe388
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Last year' = espInvoiceLine[Year]-1
		formatString: 0
		lineageTag: e55cf43e-8b29-41c0-bc84-6393397db6c9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SumLastYearSales = ```
			
			CALCULATE(
			    SUM(espInvoiceLine[Total Sales]), 
			    FILTER(
			        ALL(espInvoiceLine),
			        espInvoiceLine[Month Year] = EARLIER(espInvoiceLine[Month Last Year])
			    )
			)
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 37e286a6-ecf5-4226-b552-3280acd3b5ba
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Month Last Year' = espInvoiceLine[Month] & " " & espInvoiceLine[Last year]
		lineageTag: 3ac5734a-b676-42a5-aeed-9e223aa8a3b7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'espInvoice.orgCompany.ID'
		dataType: int64
		formatString: 0
		lineageTag: c8f93d89-64b1-4518-8aad-f9b73f5e9285
		summarizeBy: count
		sourceColumn: espInvoice.orgCompany.ID

		annotation SummarizationSetBy = Automatic

	column 'espInvoice.orgCompany.name'
		dataType: string
		lineageTag: 6ee4aebc-9f05-4e61-90d5-b5484a7ed928
		summarizeBy: none
		sourceColumn: espInvoice.orgCompany.name

		annotation SummarizationSetBy = Automatic

	column FirstDayOfMonth = ```
			DATE(YEAR(espInvoiceLine[espInvoice.transactiondate]), MONTH(espInvoiceLine[espInvoice.transactiondate]), 1)
			
			
			```
		formatString: Short Date
		lineageTag: 4d6f48af-68b8-44a4-9765-8c66dff5e1ba
		summarizeBy: none

		variation Variation
			isDefault
			relationship: a6495ab3-b0da-4004-a2d9-53136d3c9877
			defaultHierarchy: LocalDateTable_e40ed00c-8254-4f3d-944a-ea17676198d5.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Month Date' = ```
			EOMONTH(espInvoiceLine[espInvoice.transactiondate],0)
			
			```
		formatString: Short Date
		lineageTag: 14ec9c34-2a41-450d-9afc-8b482eef7b6c
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 9d48cc4e-9804-4861-aa52-9d9176cd33ac
			defaultHierarchy: LocalDateTable_fd49972d-ad85-4796-a23a-e6d300bcfaa8.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number' = MONTH(espInvoiceLine[espInvoice.transactiondate])
		formatString: 0
		lineageTag: 2f3afaac-bbcd-4324-b79b-89bc75cf57e1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column MSF = espInvoiceLine[areainvoiced]/1000
		lineageTag: 1e15847e-dfe8-4dbb-b576-50a3daf42ace
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales $ per MSF' = IFERROR(espInvoiceLine[Total Sales]/espInvoiceLine[MSF],BLANK())
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 26e67f43-0b97-4bf4-ae29-0d345cd40407
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'espOrder.length'
		dataType: int64
		formatString: 0
		lineageTag: e6a38066-c5c1-4242-81e7-f09d9decc626
		summarizeBy: sum
		sourceColumn: espOrder.length

		annotation SummarizationSetBy = Automatic

	column 'espOrder.width'
		dataType: int64
		formatString: 0
		lineageTag: 91f92f8d-92dc-44c9-9dc5-a6d2a95becc7
		summarizeBy: sum
		sourceColumn: espOrder.width

		annotation SummarizationSetBy = Automatic

	column spec = RELATED(dwproductionorders[spec_number])
		lineageTag: cd29e503-66ad-48bd-91e7-314845366976
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Price per piece' = If(espInvoiceLine[invoiceLineType] = "Goods Invoice Line", IFERROR(espInvoiceLine[Total Sales]/espInvoiceLine[quantity],BLANK()),blank())
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6e0961dd-3247-459a-b6b2-17f8d64c9ef1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Quantity2 = espInvoiceLine[quantity]
		lineageTag: 78aca02a-cfe4-46ad-8368-4ab6f5d1adee
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Has_Related_Production_Order = ```
			
			IF(
			    NOT(ISBLANK(RELATED(dwproductionorders[job_number]))), 
			    TRUE, 
			    FALSE
			)
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 477340e8-805c-480a-8a2c-31b6fe338d79
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column count = ```
			DISTINCTCOUNT(espInvoiceLine[Job Number])
			
			```
		formatString: 0
		lineageTag: 126873a9-e9ac-4a68-8217-79db7c683da2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'job num' = ```
			espInvoiceLine[Job Number]   
			```
		lineageTag: b0964888-88c7-48d1-a72a-abe2ccb405cf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition espInvoiceLine = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.1.12"),
				    esp = Source{[Name="esp"]}[Data],
				    dbo_espInvoiceLine = esp{[Schema="dbo",Item="espInvoiceLine"]}[Data],
				    #"Expanded espOrder" = Table.ExpandRecordColumn(dbo_espInvoiceLine, "espOrder", {"jobnumber", "length", "width", "freight", "cstCostEstimate(precostestimateID)"}, {"espOrder.jobnumber", "espOrder.length", "espOrder.width", "espOrder.freight", "espOrder.cstCostEstimate(precostestimateID)"}),
				    #"Expanded espInvoice" = Table.ExpandRecordColumn(#"Expanded espOrder", "espInvoice", {"transactiondate", "orgCompany"}, {"espInvoice.transactiondate", "espInvoice.orgCompany"}),
				    #"Expanded espInvoice.orgCompany" = Table.ExpandRecordColumn(#"Expanded espInvoice", "espInvoice.orgCompany", {"ID", "name"}, {"espInvoice.orgCompany.ID", "espInvoice.orgCompany.name"}),
				    #"Expanded espOrder.cstCostEstimate(precostestimateID)" = Table.ExpandRecordColumn(#"Expanded espInvoice.orgCompany", "espOrder.cstCostEstimate(precostestimateID)", {"ID"}, {"espOrder.cstCostEstimate(precostestimateID).ID"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded espOrder.cstCostEstimate(precostestimateID)",{"mainttime", "userID", "comments", "costivl01", "costivl02", "costivl03", "costivl04", "costivl05", "costivl06", "costivl07", "costivl08", "costivl09", "costivl10", "costivl11", "costivl12", "iscosted", "usernumivl01", "usernumivl02", "usernumivl03", "usernumivl04", "usernumivl05", "usercodeivl01", "usercodeivl02", "usercodeivl03", "usercodeivl04", "usercodeivl05", "plantID", "purchaseOrderID", "productCode", "gLCode", "foreigndiscount", "foreigngoodsvalue", "totalforeignvalue", "priceperitem", "tradediscountvalue", "goodsvalue", "salestax1", "salestax2", "salestax3", "totalsalestax", "description", "unitprice", "perUnitUOM", "issueItemID", "levyRateID", "taxproductgroupID", "costivl13", "costivl14", "costivl15", "costivl16", "costivl17", "costivl18", "costivl19", "costivl20", "costivl21", "costivl22", "costivl23", "costivl24", "costivl25", "costivl26", "costivl27", "costivl28", "costivl29", "costivl30", "costivl31", "costivl32", "costivl33", "costivl34", "costivl35", "costivl36", "costivl37", "costivl38", "costivl39", "costivl40", "quantityamortized", "commission", "toolcharge", "interestcharge", "salestax4", "salestax5", "salestax6", "ispriceconsolidated", "linenumber", "exchangeRateID"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"espInvoice.transactiondate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

