table espOrder
	lineageTag: 845edc69-07ad-4f11-918a-ac3a56f59537

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 61d7ff40-9383-4e9e-ba9c-73a064b3456a
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column jobnumber
		dataType: string
		lineageTag: 53a6304b-9614-45e2-8a09-b8ca1c9df66f
		summarizeBy: none
		sourceColumn: jobnumber

		annotation SummarizationSetBy = Automatic

	column precostestimateID
		dataType: int64
		formatString: 0
		lineageTag: e74bf59c-543c-4033-8432-e18900edea7f
		summarizeBy: count
		sourceColumn: precostestimateID

		annotation SummarizationSetBy = Automatic

	column 'Pre Material Cost (Per Unit)'
		dataType: double
		lineageTag: 3e7c11a5-d097-4e70-8971-1865eee91ea8
		summarizeBy: sum
		sourceColumn: Pre Material Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pre Labor Cost (Per Unit)'
		dataType: double
		lineageTag: 76f7c288-589b-4c67-816f-97d743e6d27d
		summarizeBy: sum
		sourceColumn: Pre Labor Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pre Freight Cost (Per Unit)'
		dataType: double
		lineageTag: 371b4a03-5b83-42a6-912c-51c180a6136e
		summarizeBy: sum
		sourceColumn: Pre Freight Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pre Full Cost (Per Unit)'
		dataType: double
		lineageTag: cc6c54bf-8bdd-40a6-9d84-e5d611a4bc30
		summarizeBy: sum
		sourceColumn: Pre Full Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pre Other Direct Cost (Per Unit)'
		dataType: double
		lineageTag: 93d76ecf-d940-497a-b3f1-168f57e6baa0
		summarizeBy: sum
		sourceColumn: Pre Other Direct Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pre Other Indirect Cost (Per Unit)'
		dataType: double
		lineageTag: 39423909-d0a0-47cb-96f1-18b40c6c7ba8
		summarizeBy: sum
		sourceColumn: Pre Other Indirect Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column orderedquantity
		dataType: int64
		formatString: 0
		lineageTag: f5d285e9-b8a8-4fa1-8ff7-25546b65a4f8
		summarizeBy: sum
		sourceColumn: orderedquantity

		annotation SummarizationSetBy = Automatic

	column unitquantity
		dataType: int64
		formatString: 0
		lineageTag: 821af134-27a8-47d0-ab6d-974fc7c0e9ed
		summarizeBy: sum
		sourceColumn: unitquantity

		annotation SummarizationSetBy = Automatic

	column plannedquantity
		dataType: int64
		formatString: 0
		lineageTag: 8e795347-d609-43d0-b108-c06c03d1acce
		summarizeBy: sum
		sourceColumn: plannedquantity

		annotation SummarizationSetBy = Automatic

	column producedquantity
		dataType: int64
		formatString: 0
		lineageTag: 54be365c-a022-45de-9d31-306867beca3f
		summarizeBy: sum
		sourceColumn: producedquantity

		annotation SummarizationSetBy = Automatic

	column shippedquantity
		dataType: int64
		formatString: 0
		lineageTag: 1d10ba87-754a-42ef-88c2-b9bc8b2b0373
		summarizeBy: sum
		sourceColumn: shippedquantity

		annotation SummarizationSetBy = Automatic

	column invoicedquantity
		dataType: int64
		formatString: 0
		lineageTag: c4653b68-2f2f-4149-b1b6-61f85001b0d5
		summarizeBy: sum
		sourceColumn: invoicedquantity

		annotation SummarizationSetBy = Automatic

	column totallength
		dataType: double
		lineageTag: 3b18cd95-2dd8-4d26-a1bc-6cc2109b5e71
		summarizeBy: sum
		sourceColumn: totallength

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column totalarea
		dataType: double
		lineageTag: a36875f3-0a42-4a0a-ab61-3c9c727f6b34
		summarizeBy: sum
		sourceColumn: totalarea

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column totalweight
		dataType: double
		lineageTag: b00b76dc-437f-4b3e-bd35-99b1ba192b17
		summarizeBy: sum
		sourceColumn: totalweight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column autoperunitUOM
		dataType: string
		lineageTag: 43bfd6ce-ba2d-426d-bdf9-bc211c802b2e
		summarizeBy: none
		sourceColumn: autoperunitUOM

		annotation SummarizationSetBy = Automatic

	column perUnitUOM
		dataType: string
		lineageTag: 5b9958c2-caa8-4d83-b1bd-160079aee6d4
		summarizeBy: none
		sourceColumn: perUnitUOM

		annotation SummarizationSetBy = Automatic

	column companyID
		dataType: int64
		formatString: 0
		lineageTag: b097e326-0559-428f-9dc0-a4c34bb97e86
		summarizeBy: count
		sourceColumn: companyID

		annotation SummarizationSetBy = Automatic

	column contactID
		dataType: int64
		formatString: 0
		lineageTag: 2dbbbe9e-d375-4a39-a55a-e1405bce08a7
		summarizeBy: count
		sourceColumn: contactID

		annotation SummarizationSetBy = Automatic

	column productpriceID
		dataType: int64
		formatString: 0
		lineageTag: d2ec5ba6-e235-41ab-890f-fac8e3db57e1
		summarizeBy: count
		sourceColumn: productpriceID

		annotation SummarizationSetBy = Automatic

	column orderstatus
		dataType: string
		lineageTag: 9275fca3-f456-437b-97dd-71c16409d706
		summarizeBy: none
		sourceColumn: orderstatus

		annotation SummarizationSetBy = Automatic

	column 'Post Material Cost (Per Unit)'
		dataType: double
		lineageTag: 4663832a-ca22-4d79-8dea-f2163fa29c6c
		summarizeBy: sum
		sourceColumn: Post Material Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Post Labor Cost (Per Unit)'
		dataType: double
		lineageTag: f861c95e-d46b-4bd0-86e6-846b6eaa1750
		summarizeBy: sum
		sourceColumn: Post Labor Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Post Freight Cost (Per Unit)'
		dataType: double
		lineageTag: 6c511f0e-9cbf-4b64-83dc-2519f9ca7045
		summarizeBy: sum
		sourceColumn: Post Freight Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Post Other Direct Cost (Per Unit)'
		dataType: double
		lineageTag: 7db541a8-d9f2-4120-a51b-bfa1717acd54
		summarizeBy: sum
		sourceColumn: Post Other Direct Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Post Other Indirect Cost (Per Unit)'
		dataType: double
		lineageTag: 27b73cce-292a-49c1-a9cf-521c278de0aa
		summarizeBy: sum
		sourceColumn: Post Other Indirect Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Post Full Cost (Per Unit)'
		dataType: double
		lineageTag: 63df9162-5b15-484b-a96b-7be82f0889b7
		summarizeBy: sum
		sourceColumn: Post Full Cost (Per Unit)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Spec Number' = RELATED(dwproductionorders[spec_number])
		lineageTag: 4d066eb7-2330-4459-a6cd-532778378ee1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition espOrder = m
		mode: import
		source =
				let
				    // =============================
				    // Source
				    // =============================
				    Source = Sql.Databases("192.168.1.12"),
				    EspDb = Source{[Name="esp"]}[Data],
				    OrdersRaw = EspDb{[Schema="dbo", Item="espOrder"]}[Data],
				
				    // =============================
				    // Keep only the columns we want from espOrder (add/remove as needed)
				    // NOTE: include the nav properties used later
				    // =============================
				    KeepOrderColumns =
				        {
				            "ID",
				            "jobnumber",
				            "orderedquantity",
				            "unitquantity",
				            "plannedquantity",
				            "producedquantity",
				            "shippedquantity",
				            "invoicedquantity",
				            "totallength",
				            "totalarea",
				            "totalweight",
				            "autoperunitUOM",
				            "perUnitUOM",
				            "companyID",
				            "contactID",
				            "precostestimateID",
				            "productpriceID",
				            "orderstatus",
				            "versionTimeStamp",
				            "cstCostEstimate(precostestimateID)",
				            "ocsPostcostedorder"
				        },
				
				    Orders =
				        Table.SelectColumns(
				            OrdersRaw,
				            List.Intersect({Table.ColumnNames(OrdersRaw), KeepOrderColumns})
				        ),
				
				    // =============================
				    // Expand Pre Cost Estimate (via nav property)
				    // =============================
				    ExpandedPreCost =
				        Table.ExpandRecordColumn(
				            Orders,
				            "cstCostEstimate(precostestimateID)",
				            {"materialcost", "labourcost", "freightcost", "otherdirectcost", "otherindirectcost", "fullcost"},
				            {"Pre_MaterialCost_per1000", "Pre_LaborCost_per1000", "Pre_FreightCost_per1000", "Pre_OtherDirectCost_per1000", "Pre_OtherIndirectCost_per1000", "Pre_FullCost_per1000"}
				        ),
				
				    // =============================
				    // Expand Post Cost Estimate (keep your working pattern)
				    // =============================
				    ExpandedPostCostEstimateNested =
				        Table.ExpandTableColumn(
				            ExpandedPreCost,
				            "ocsPostcostedorder",
				            {"cstCostEstimate"},
				            {"PostCostEstimateRecord"}
				        ),
				
				    ExpandedPostCost =
				        Table.ExpandRecordColumn(
				            ExpandedPostCostEstimateNested,
				            "PostCostEstimateRecord",
				            {"materialcost", "labourcost", "freightcost", "otherdirectcost", "otherindirectcost", "fullcost"},
				            {"Post_MaterialCost_per1000", "Post_LaborCost_per1000", "Post_FreightCost_per1000", "Post_OtherDirectCost_per1000", "Post_OtherIndirectCost_per1000", "Post_FullCost_per1000"}
				        ),
				
				    // =============================
				    // Convert per-1000 to per-unit
				    // =============================
				    CostsPerUnit =
				        Table.TransformColumns(
				            ExpandedPostCost,
				            {
				                {"Pre_MaterialCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Pre_LaborCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Pre_FreightCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Pre_OtherDirectCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Pre_OtherIndirectCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Pre_FullCost_per1000", each if _ = null then null else _ / 1000, type number},
				
				                {"Post_MaterialCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Post_LaborCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Post_FreightCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Post_OtherDirectCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Post_OtherIndirectCost_per1000", each if _ = null then null else _ / 1000, type number},
				                {"Post_FullCost_per1000", each if _ = null then null else _ / 1000, type number}
				            }
				        ),
				
				    // =============================
				    // Friendly names
				    // =============================
				    RenamedCosts =
				        Table.RenameColumns(
				            CostsPerUnit,
				            {
				                {"Pre_MaterialCost_per1000", "Pre Material Cost (Per Unit)"},
				                {"Pre_LaborCost_per1000", "Pre Labor Cost (Per Unit)"},
				                {"Pre_FreightCost_per1000", "Pre Freight Cost (Per Unit)"},
				                {"Pre_OtherDirectCost_per1000", "Pre Other Direct Cost (Per Unit)"},
				                {"Pre_OtherIndirectCost_per1000", "Pre Other Indirect Cost (Per Unit)"},
				                {"Pre_FullCost_per1000", "Pre Full Cost (Per Unit)"},
				
				                {"Post_MaterialCost_per1000", "Post Material Cost (Per Unit)"},
				                {"Post_LaborCost_per1000", "Post Labor Cost (Per Unit)"},
				                {"Post_FreightCost_per1000", "Post Freight Cost (Per Unit)"},
				                {"Post_OtherDirectCost_per1000", "Post Other Direct Cost (Per Unit)"},
				                {"Post_OtherIndirectCost_per1000", "Post Other Indirect Cost (Per Unit)"},
				                {"Post_FullCost_per1000", "Post Full Cost (Per Unit)"}
				            }
				        )
				
				in
				    RenamedCosts

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

